name: foody
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  rflutter_alert: ^2.0.4
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.2.0
  auth_buttons: ^1.0.1+4
  flutter_scale_tap: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/